# Generated by Django 4.0.4 on 2022-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ruta_archivo_root_archivo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='parsed',
            field=models.TextField(null=True),
        ),
    ]
