# Generated by Django 4.0.4 on 2022-05-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_archivo_parsed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='parsed',
            new_name='response',
        ),
    ]
