# Generated by Django 4.0.4 on 2022-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='ruta',
            new_name='root',
        ),
        migrations.AddField(
            model_name='archivo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
